import { Project } from './types';

export const projects: Project[] = [
  {
    title: 'Bremont',
    src1: 'bremont/bremont1.webm',
    src2: 'bremont/bremont2.webm',
    src3: 'bremont/bremont3.webm',
    color: '#dbeafe',
    url: 'https://us.bremont.com/',
    role: 'Senior Shopify Engineer',
  },
  {
    title: 'BURGA',
    src1: 'burga/burga1.webm',
    src2: 'burga/burga2.webm',
    src3: 'burga/burga3.webm',
    color: '#ddd6fe',
    url: 'https://burga.com/',
    role: 'Full Stack Shopify Developer',
  },
  {
    title: 'Daniel Wellington',
    src1: 'danielwellington/danielwellington1.webm',
    src2: 'danielwellington/danielwellington2.webm',
    src3: 'danielwellington/danielwellington3.webm',
    color: '#fae8ff',
    url: 'https://us.danielwellington.com/',
    role: 'Shopify / Shopify API Engineer',
  },
  {
    title: 'Happy Earth Tea',
    src1: 'happyearthtea/happyearthtea1.webm',
    src2: 'happyearthtea/happyearthtea2.webm',
    src3: 'happyearthtea/happyearthtea3.webm',
    color: '#fee2e2',
    url: 'https://happyearthtea.com/',
    role: 'Full Stack Ecommerce Developer',
  },
  {
    title: 'HAUS',
    src1: 'haus/haus1.webm',
    src2: 'haus/haus2.webm',
    src3: 'haus/haus3.webm',
    color: '#dbeafe',
    url: 'https://hauslondon.com/',
    role: 'Application Developer',
  },
  {
    title: 'PIMAX',
    src1: 'pimax/pimax1.webm',
    src2: 'pimax/pimax2.webm',
    src3: 'pimax/pimax3.webm',
    color: '#ddd6fe',
    url: 'https://pimax.com/',
    role: 'Shopify Engineer',
  },
  {
    title: 'SAVOTTA',
    src1: 'savotta/savotta1.webm',
    src2: 'savotta/savotta2.webm',
    src3: 'savotta/savotta3.webm',
    color: '#ffedd5',
    url: 'https://www.savotta.fi/',
    role: 'Senior Shopify Developer',
  },
  {
    title: 'Studio Proper',
    src1: 'studioproper/studioproper1.webm',
    src2: 'studioproper/studioproper2.webm',
    src3: 'studioproper/studioproper3.webm',
    color: '#ecfccb',
    url: 'https://www.studioproper.com/',
    role: 'Shopify Developer',
  },
  {
    title: 'TOYSRUS',
    src1: 'toysrus/toysrus1.webm',
    src2: 'toysrus/toysrus2.webm',
    src3: 'toysrus/toysrus3.webm',
    color: '#ecfccb',
    url: 'https://www.toysrus.com/',
    role: 'Shopify CRO Expert',
  },
  {
    title: 'WP Standard',
    src1: 'wpstandard/wpstandard1.webm',
    src2: 'wpstandard/wpstandard2.webm',
    src3: 'wpstandard/wpstandard3.webm',
    color: '#ecfccb',
    url: 'https://wpstandard.com/',
    role: 'Full Stack Engineer',
  },
];
